language: node_js
node_js:
- 12
- 14
cache:
  npm: false
script:
- npm run test-travis
- npm run lint
deploy:
- provider: script
  skip_cleanup: true
  # script: npx -p @qiwi/semrel-toolkit multi-semrel
  on:
    node: 12
    branch: main
