openapi: 3.0.3
info:
  title: Examples name should not contain space
  description: Examples name should not contain space
  version: 1.0.0
servers:
  - url: 'https://example.com'
paths:
  '/v1/users':
    get:
      operationId: get_users
      summary: returns user list
      responses:
        200:
          description: returns list of users
          content:
            'application/json':
              schema:
                properties:
                  id:
                    type: string
              examples:
                'with quotes':
                  summary: 'successful example'
                  value: 'success value'
                without quotes:
                  summary: 'successful example'
                  value: 'success value'

